
services:


  react:
    build: 
      context: ./frontend
    volumes:
      - ./frontend:/app
    networks:
      - request-network
    ports:
      - "5173:5173"

  spring-boot:
    build: 
      context: ./backend
    networks:
      - request-network
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    depends_on:
      - react



networks:
  request-network:
    driver: bridge


