name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze with JaCoCo coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Capture JaCoCo Report Path
        run: |
          JACOCO_REPORT_PATH=$(find . -name "jacoco.xml")
          echo "JACOCO_REPORT_PATH=$JACOCO_REPORT_PATH" >> $GITHUB_ENV
      - name: Build and analyze with JaCoCo coverage
        env:
          JACOCO_REPORT_PATH: ${{ env.JACOCO_REPORT_PATH }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd hw1/backend
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=FiNeX96_TQS_108969 \
            -Dsonar.java.coveragePlugin=jacoco \
            -Dsonar.jacoco.reportPaths=$JACOCO_REPORT_PATH